"""Lightweight schema defaults for config-driven CLI wrappers.

This keeps the first phase explicit and simple while preserving legacy behavior.
"""

DEFAULTS = {
    "model": {
        "name_or_path": "facebook/wav2vec2-xls-r-300m",
    },
    "dataset": {
        "type": "hf",
        "name": "pengyizhou/nsc-imda-part6",
        "config": None,
        "train_split": "train",
        "val_split": "validation",
        "test_split": "test",
        "audio_col": "audio",
        "text_col": "text",
        "test_audio_col": "audio",
        "test_text_col": None,
    },
    "transcripts": {
        "source": "dataset_field",
        "pseudo_jsonl": None,
        "pseudo_dev_jsonl": None,
        "pseudo_audio_col": "audio_path",
        "pseudo_join_on_hf_id": True,
        "pseudo_hf_id_col": "id",
        "pseudo_hf_splits": "train,validation",
        "disallow_test_split_in_pseudo_join": True,
        "pseudo_score_col": "score",
        "pseudo_min_score": 0.0,
    },
    "normalization": {
        "use_text_normalizer": True,
        "normalizer_yaml": None,
    },
    "vocab": {
        "out_path": "artifacts/vocab/vocab_shared.json",
        "mode": "dataset_only",
        "score_col": "score",
        "min_score": 0.0,
        "aux_score_col": "score",
        "aux_min_score": 0.0,
    },
    "training": {
        "out_dir": "runs/xlsr300m_dev",
        "max_sec": 30.0,
        "num_proc": 4,
        "seed": 42,
        "val_size": 0.1,
        "bs": 32,
        "grad_accum": 1,
        "lr": 3e-5,
        "epochs": 20.0,
        "lr_scheduler": "cosine",
        "warmup_ratio": 0.1,
        "weight_decay": 0.01,
        "max_grad_norm": 1.0,
        "eval_steps": 1200,
        "save_steps": 1200,
        "logging_steps": 50,
        "save_total_limit": 4,
        "best_metric": "wer_decoded_norm",
    },
    "eval": {
        "split": "test",
        "audio_col": "audio",
        "text_col": "text",
        "id_col": "id",
        "batch_size": 16,
        "num_workers": 4,
        "num_samples": 0,
        "max_sec": 0.0,
        "discard_number_samples": False,
        "use_text_normalizer": True,
        "normalizer_yaml": None,
        "space_chinese_chars": True,
        "verbalize_numbers": False,
        "device": "auto",
        "out_json": "eval_outputs/metrics.json",
        "out_jsonl": "eval_outputs/preds.jsonl",
    },
}
